services:
  backend:
    build: ./backend
    ports:
      - "5000:3000"

  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8085:80"
