services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
